"""add_codigo_autor_emenda

Revision ID: add_codigo_autor_emenda
Revises: 
Create Date: 2025-11-04 22:37:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_codigo_autor_emenda'
down_revision = None  # Migration independente
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deputados', sa.Column('codigo_autor_emenda', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_deputados_codigo_autor_emenda'), 'deputados', ['codigo_autor_emenda'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deputados_codigo_autor_emenda'), table_name='deputados')
    op.drop_column('deputados', 'codigo_autor_emenda')
    # ### end Alembic commands ###
