"""Adicionar tabelas de remuneração e emendas parlamentares

Revision ID: adicionar_remuneracao_emendas
Revises: ff0d9e1674b7
Create Date: 2025-10-15 20:26:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adicionar_remuneracao_emendas'
down_revision = 'ff0d9e1674b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Tabelas de remuneração
    op.create_table('remuneracoes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('deputado_id', sa.Integer(), nullable=False),
        sa.Column('ano', sa.Integer(), nullable=False),
        sa.Column('mes', sa.Integer(), nullable=False),
        sa.Column('salario_base', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('auxilio_moradia', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('auxilio_saude', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('auxilio_alimentacao', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('verbas_indenizatorias_total', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('diarias_total', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('passagens_total', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('possui_cargo_comissao', sa.Boolean(), nullable=True),
        sa.Column('cargo_comissao', sa.String(length=255), nullable=True),
        sa.Column('adicional_comissao', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('total_bruto', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('total_liquido', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remuneracoes_ano'), 'remuneracoes', ['ano'], unique=False)
    op.create_index(op.f('ix_remuneracoes_id'), 'remuneracoes', ['id'], unique=False)
    op.create_index(op.f('ix_remuneracoes_mes'), 'remuneracoes', ['mes'], unique=False)
    
    op.create_table('verbas_indenizatorias',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('deputado_id', sa.Integer(), nullable=False),
        sa.Column('remuneracao_id', sa.Integer(), nullable=True),
        sa.Column('tipo_verba', sa.String(length=100), nullable=False),
        sa.Column('codigo_verba', sa.String(length=20), nullable=True),
        sa.Column('descricao', sa.Text(), nullable=True),
        sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('valor_reembolsado', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('ano', sa.Integer(), nullable=False),
        sa.Column('mes', sa.Integer(), nullable=False),
        sa.Column('data_referencia', sa.Date(), nullable=True),
        sa.Column('api_camara_id', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['remuneracao_id'], ['remuneracoes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verbas_indenizatorias_ano'), 'verbas_indenizatorias', ['ano'], unique=False)
    op.create_index(op.f('ix_verbas_indenizatorias_id'), 'verbas_indenizatorias', ['id'], unique=False)
    op.create_index(op.f('ix_verbas_indenizatorias_mes'), 'verbas_indenizatorias', ['mes'], unique=False)
    op.create_index(op.f('ix_verbas_indenizatorias_tipo_verba'), 'verbas_indenizatorias', ['tipo_verba'], unique=False)
    
    op.create_table('cargos_comissoes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('deputado_id', sa.Integer(), nullable=False),
        sa.Column('orgao_id', sa.Integer(), nullable=True),
        sa.Column('orgao_nome', sa.String(length=255), nullable=False),
        sa.Column('orgao_sigla', sa.String(length=20), nullable=True),
        sa.Column('cargo', sa.String(length=100), nullable=False),
        sa.Column('data_inicio', sa.Date(), nullable=False),
        sa.Column('data_fim', sa.Date(), nullable=True),
        sa.Column('cargo_ativo', sa.Boolean(), nullable=True),
        sa.Column('adicional_remuneratorio', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('auxilio_presenca', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('api_camara_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargos_comissoes_id'), 'cargos_comissoes', ['id'], unique=False)
    
    op.create_table('salarios_padrao',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ano', sa.Integer(), nullable=False),
        sa.Column('mes_inicio', sa.Integer(), nullable=True),
        sa.Column('salario_bruto', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('auxilio_moradia_maximo', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('auxilio_saude_maximo', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('diaria_maxima', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('fonte_informacao', sa.String(length=255), nullable=True),
        sa.Column('data_publicacao', sa.Date(), nullable=True),
        sa.Column('observacoes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('ano')
    )
    op.create_index(op.f('ix_salarios_padrao_id'), 'salarios_padrao', ['id'], unique=False)
    
    # Tabelas de emendas
    op.create_table('emendas_parlamentares',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('api_camara_id', sa.Integer(), nullable=False),
        sa.Column('deputado_id', sa.Integer(), nullable=False),
        sa.Column('tipo_emenda', sa.String(length=50), nullable=False),
        sa.Column('numero', sa.Integer(), nullable=False),
        sa.Column('ano', sa.Integer(), nullable=False),
        sa.Column('emenda', sa.Text(), nullable=False),
        sa.Column('local', sa.String(length=100), nullable=True),
        sa.Column('natureza', sa.String(length=100), nullable=True),
        sa.Column('tema', sa.String(length=255), nullable=True),
        sa.Column('area_tematica', sa.String(length=100), nullable=True),
        sa.Column('valor_emenda', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('valor_empenhado', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('valor_liquidado', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('valor_pago', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('beneficiario_principal', sa.Text(), nullable=True),
        sa.Column('beneficiarios_secundarios', sa.Text(), nullable=True),
        sa.Column('uf_beneficiario', sa.String(length=2), nullable=True),
        sa.Column('municipio_beneficiario', sa.String(length=255), nullable=True),
        sa.Column('situacao', sa.String(length=100), nullable=True),
        sa.Column('data_apresentacao', sa.Date(), nullable=True),
        sa.Column('data_aprovacao', sa.Date(), nullable=True),
        sa.Column('data_publicacao', sa.Date(), nullable=True),
        sa.Column('autor', sa.String(length=255), nullable=True),
        sa.Column('partido_autor', sa.String(length=20), nullable=True),
        sa.Column('uf_autor', sa.String(length=2), nullable=True),
        sa.Column('url_documento', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('api_camara_id')
    )
    op.create_index(op.f('ix_emendas_parlamentares_ano'), 'emendas_parlamentares', ['ano'], unique=False)
    op.create_index(op.f('ix_emendas_parlamentares_id'), 'emendas_parlamentares', ['id'], unique=False)
    op.create_index(op.f('ix_emendas_parlamentares_situacao'), 'emendas_parlamentares', ['situacao'], unique=False)
    op.create_index(op.f('ix_emendas_parlamentares_tipo_emenda'), 'emendas_parlamentares', ['tipo_emenda'], unique=False)
    op.create_index(op.f('ix_emendas_parlamentares_api_camara_id'), 'emendas_parlamentares', ['api_camara_id'], unique=True)
    
    op.create_table('detalhes_emendas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('emenda_id', sa.Integer(), nullable=False),
        sa.Column('numero_lei', sa.String(length=20), nullable=True),
        sa.Column('ementa', sa.Text(), nullable=True),
        sa.Column('justificativa', sa.Text(), nullable=True),
        sa.Column('objetivo', sa.Text(), nullable=True),
        sa.Column('funcao', sa.String(length=100), nullable=True),
        sa.Column('subfuncao', sa.String(length=100), nullable=True),
        sa.Column('programa', sa.String(length=100), nullable=True),
        sa.Column('acao', sa.String(length=100), nullable=True),
        sa.Column('orgao_responsavel', sa.String(length=255), nullable=True),
        sa.Column('unidade_orcamentaria', sa.String(length=255), nullable=True),
        sa.Column('categoria_economica', sa.String(length=100), nullable=True),
        sa.Column('fonte_recursos', sa.String(length=100), nullable=True),
        sa.Column('texto_completo', sa.Text(), nullable=True),
        sa.Column('pdf_url', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['emenda_id'], ['emendas_parlamentares.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalhes_emendas_id'), 'detalhes_emendas', ['id'], unique=False)
    
    op.create_table('votacoes_emendas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('emenda_id', sa.Integer(), nullable=False),
        sa.Column('data_votacao', sa.Date(), nullable=True),
        sa.Column('hora_votacao', sa.String(length=10), nullable=True),
        sa.Column('tipo_votacao', sa.String(length=100), nullable=True),
        sa.Column('resultado', sa.String(length=50), nullable=True),
        sa.Column('votos_sim', sa.Integer(), nullable=True),
        sa.Column('votos_nao', sa.Integer(), nullable=True),
        sa.Column('votos_abstencao', sa.Integer(), nullable=True),
        sa.Column('total_votantes', sa.Integer(), nullable=True),
        sa.Column('orgao_votacao', sa.String(length=255), nullable=True),
        sa.Column('plenario', sa.Boolean(), nullable=True),
        sa.Column('api_camara_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['emenda_id'], ['emendas_parlamentares.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_votacoes_emendas_id'), 'votacoes_emendas', ['id'], unique=False)
    
    op.create_table('execucao_emendas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('emenda_id', sa.Integer(), nullable=False),
        sa.Column('ano_execucao', sa.Integer(), nullable=False),
        sa.Column('mes_execucao', sa.Integer(), nullable=True),
        sa.Column('data_referencia', sa.Date(), nullable=True),
        sa.Column('valor_empenhado_acumulado', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('valor_liquidado_acumulado', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('valor_pago_acumulado', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('percentual_empenhado', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('percentual_liquidado', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('percentual_pago', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('status_execucao', sa.String(length=50), nullable=True),
        sa.Column('observacoes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['emenda_id'], ['emendas_parlamentares.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execucao_emendas_ano_execucao'), 'execucao_emendas', ['ano_execucao'], unique=False)
    op.create_index(op.f('ix_execucao_emendas_id'), 'execucao_emendas', ['id'], unique=False)
    
    op.create_table('ranking_emendas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('deputado_id', sa.Integer(), nullable=False),
        sa.Column('ano_referencia', sa.Integer(), nullable=False),
        sa.Column('mes_referencia', sa.Integer(), nullable=True),
        sa.Column('quantidade_emendas', sa.Integer(), nullable=True),
        sa.Column('valor_total_emendas', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('valor_medio_emenda', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('valor_total_executado', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('percentual_execucao_medio', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('ranking_quantidade', sa.Integer(), nullable=True),
        sa.Column('ranking_valor', sa.Integer(), nullable=True),
        sa.Column('ranking_execucao', sa.Integer(), nullable=True),
        sa.Column('quantidade_municipios_beneficiados', sa.Integer(), nullable=True),
        sa.Column('quantidade_ufs_beneficiadas', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ranking_emendas_ano_referencia'), 'ranking_emendas', ['ano_referencia'], unique=False)
    op.create_index(op.f('ix_ranking_emendas_id'), 'ranking_emendas', ['id'], unique=False)
    op.create_index(op.f('ix_ranking_emendas_mes_referencia'), 'ranking_emendas', ['mes_referencia'], unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ranking_emendas_mes_referencia'), table_name='ranking_emendas')
    op.drop_index(op.f('ix_ranking_emendas_id'), table_name='ranking_emendas')
    op.drop_index(op.f('ix_ranking_emendas_ano_referencia'), table_name='ranking_emendas')
    op.drop_table('ranking_emendas')
    op.drop_index(op.f('ix_execucao_emendas_id'), table_name='execucao_emendas')
    op.drop_index(op.f('ix_execucao_emendas_ano_execucao'), table_name='execucao_emendas')
    op.drop_table('execucao_emendas')
    op.drop_index(op.f('ix_votacoes_emendas_id'), table_name='votacoes_emendas')
    op.drop_table('votacoes_emendas')
    op.drop_index(op.f('ix_detalhes_emendas_id'), table_name='detalhes_emendas')
    op.drop_table('detalhes_emendas')
    op.drop_index(op.f('ix_emendas_parlamentares_api_camara_id'), table_name='emendas_parlamentares')
    op.drop_index(op.f('ix_emendas_parlamentares_tipo_emenda'), table_name='emendas_parlamentares')
    op.drop_index(op.f('ix_emendas_parlamentares_situacao'), table_name='emendas_parlamentares')
    op.drop_index(op.f('ix_emendas_parlamentares_ano'), table_name='emendas_parlamentares')
    op.drop_index(op.f('ix_emendas_parlamentares_id'), table_name='emendas_parlamentares')
    op.drop_table('emendas_parlamentares')
    op.drop_index(op.f('ix_salarios_padrao_id'), table_name='salarios_padrao')
    op.drop_table('salarios_padrao')
    op.drop_index(op.f('ix_cargos_comissoes_id'), table_name='cargos_comissoes')
    op.drop_table('cargos_comissoes')
    op.drop_index(op.f('ix_verbas_indenizatorias_tipo_verba'), table_name='verbas_indenizatorias')
    op.drop_index(op.f('ix_verbas_indenizatorias_mes'), table_name='verbas_indenizatorias')
    op.drop_index(op.f('ix_verbas_indenizatorias_ano'), table_name='verbas_indenizatorias')
    op.drop_index(op.f('ix_verbas_indenizatorias_id'), table_name='verbas_indenizatorias')
    op.drop_table('verbas_indenizatorias')
    op.drop_index(op.f('ix_remuneracoes_mes'), table_name='remuneracoes')
    op.drop_index(op.f('ix_remuneracoes_id'), table_name='remuneracoes')
    op.drop_index(op.f('ix_remuneracoes_ano'), table_name='remuneracoes')
    op.drop_table('remuneracoes')
    # ### end Alembic commands ###
