"""alterar_api_camara_id_para_string_manual

Revision ID: alterar_api_camara_id_para_string
Revises: adicionar_remuneracao_emendas
Create Date: 2025-10-15 21:46:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fix_api_camara_id_str'
down_revision: Union[str, Sequence[str], None] = 'adicionar_remuneracao_emendas'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - altera api_camara_id para String de forma segura."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Alterar api_camara_id na tabela emendas_parlamentares
    op.alter_column('emendas_parlamentares', 'api_camara_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(50),
                    existing_nullable=False,
                    existing_server_default=False)
    
    # Alterar api_camara_id na tabela verbas_indenizatorias
    op.alter_column('verbas_indenizatorias', 'api_camara_id',
                    existing_type=sa.String(50),
                    type_=sa.String(50),
                    existing_nullable=True)
    
    # Alterar api_camara_id na tabela cargos_comissoes
    op.alter_column('cargos_comissoes', 'api_camara_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(50),
                    existing_nullable=True)
    
    # Alterar api_camara_id na tabela votacoes_emendas
    op.alter_column('votacoes_emendas', 'api_camara_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(50),
                    existing_nullable=True)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - volta api_camara_id para Integer."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Voltar api_camara_id para Integer na tabela emendas_parlamentares
    op.alter_column('emendas_parlamentares', 'api_camara_id',
                    existing_type=sa.String(50),
                    type_=sa.INTEGER(),
                    existing_nullable=False,
                    existing_server_default=False)
    
    # Voltar api_camara_id para String na tabela verbas_indenizatorias (já era String)
    op.alter_column('verbas_indenizatorias', 'api_camara_id',
                    existing_type=sa.String(50),
                    type_=sa.String(50),
                    existing_nullable=True)
    
    # Voltar api_camara_id para Integer na tabela cargos_comissoes
    op.alter_column('cargos_comissoes', 'api_camara_id',
                    existing_type=sa.String(50),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    
    # Voltar api_camara_id para Integer na tabela votacoes_emendas
    op.alter_column('votacoes_emendas', 'api_camara_id',
                    existing_type=sa.String(50),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    
    # ### end Alembic commands ###
