"""criar_tabelas_frequencia_deputados

Revision ID: criar_frequencia
Revises: 5b97b3c5d341
Create Date: 2025-10-25 02:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'criar_frequencia'
down_revision: Union[str, Sequence[str], None] = '5b97b3c5d341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - cria tabelas de frequência de deputados."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Tabela principal de frequência mensal
    op.create_table('frequencia_deputados',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('deputado_id', sa.Integer(), nullable=False),
        sa.Column('ano', sa.Integer(), nullable=False),
        sa.Column('mes', sa.Integer(), nullable=False),
        sa.Column('dias_trabalhados', sa.Integer(), nullable=True, default=0),
        sa.Column('dias_recesso', sa.Integer(), nullable=True, default=0),
        sa.Column('faltas_justificadas', sa.Integer(), nullable=True, default=0),
        sa.Column('faltas_nao_justificadas', sa.Integer(), nullable=True, default=0),
        sa.Column('licencas', sa.Integer(), nullable=True, default=0),
        sa.Column('sessoes_plenario', sa.Integer(), nullable=True, default=0),
        sa.Column('sessoes_comissoes', sa.Integer(), nullable=True, default=0),
        sa.Column('percentual_presenca', sa.Numeric(precision=5, scale=2), nullable=True, default=0),
        sa.Column('percentual_comparecimento', sa.Numeric(precision=5, scale=2), nullable=True, default=0),
        sa.Column('data_ultima_atualizacao', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.Column('fonte_dados', sa.String(length=100), nullable=True, default='API_Camara'),
        sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('deputado_id', 'ano', 'mes', name='_frequencia_mensal_uc')
    )
    op.create_index(op.f('ix_frequencia_deputados_id'), 'frequencia_deputados', ['id'], unique=False)
    
    # Tabela de detalhes de frequência
    op.create_table('detalhes_frequencia',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('frequencia_id', sa.Integer(), nullable=False),
        sa.Column('deputado_id', sa.Integer(), nullable=False),
        sa.Column('data_evento', sa.Date(), nullable=False),
        sa.Column('tipo_evento', sa.String(length=50), nullable=False),
        sa.Column('descricao_evento', sa.String(length=255), nullable=True),
        sa.Column('presente', sa.Boolean(), nullable=True, default=False),
        sa.Column('justificado', sa.Boolean(), nullable=True, default=False),
        sa.Column('licenca', sa.Boolean(), nullable=True, default=False),
        sa.Column('tipo_presenca', sa.String(length=50), nullable=True),
        sa.Column('horario_inicio', sa.TIMESTAMP(), nullable=True),
        sa.Column('horario_fim', sa.TIMESTAMP(), nullable=True),
        sa.Column('duracao_minutos', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['frequencia_id'], ['frequencia_deputados.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('deputado_id', 'data_evento', 'tipo_evento', name='_detalhe_frequencia_uc')
    )
    op.create_index(op.f('ix_detalhes_frequencia_id'), 'detalhes_frequencia', ['id'], unique=False)
    
    # Tabela de rankings de frequência
    op.create_table('rankings_frequencia',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('frequencia_id', sa.Integer(), nullable=False),
        sa.Column('deputado_id', sa.Integer(), nullable=False),
        sa.Column('ano', sa.Integer(), nullable=False),
        sa.Column('mes', sa.Integer(), nullable=False),
        sa.Column('posicao_geral', sa.Integer(), nullable=True),
        sa.Column('posicao_partido', sa.Integer(), nullable=True),
        sa.Column('posicao_estado', sa.Integer(), nullable=True),
        sa.Column('total_deputados', sa.Integer(), nullable=True),
        sa.Column('total_deputados_partido', sa.Integer(), nullable=True),
        sa.Column('total_deputados_estado', sa.Integer(), nullable=True),
        sa.Column('percentil_geral', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('percentil_partido', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('percentil_estado', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('data_calculo', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.Column('versao_metodologia', sa.String(length=20), nullable=True, default='v1.0'),
        sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['frequencia_id'], ['frequencia_deputados.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('deputado_id', 'ano', 'mes', name='_ranking_frequencia_uc')
    )
    op.create_index(op.f('ix_rankings_frequencia_id'), 'rankings_frequencia', ['id'], unique=False)
    
    # Tabela de resumos mensais
    op.create_table('resumos_frequencia_mensal',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ano', sa.Integer(), nullable=False),
        sa.Column('mes', sa.Integer(), nullable=False),
        sa.Column('total_deputados_ativos', sa.Integer(), nullable=True, default=0),
        sa.Column('total_sessoes_realizadas', sa.Integer(), nullable=True, default=0),
        sa.Column('total_presencas', sa.Integer(), nullable=True, default=0),
        sa.Column('total_ausencias', sa.Integer(), nullable=True, default=0),
        sa.Column('media_presenca_percentual', sa.Numeric(precision=5, scale=2), nullable=True, default=0),
        sa.Column('media_dias_trabalhados', sa.Numeric(precision=5, scale=2), nullable=True, default=0),
        sa.Column('media_faltas_justificadas', sa.Numeric(precision=5, scale=2), nullable=True, default=0),
        sa.Column('media_faltas_nao_justificadas', sa.Numeric(precision=5, scale=2), nullable=True, default=0),
        sa.Column('deputados_acima_meta_presenca', sa.Integer(), nullable=True, default=0),
        sa.Column('deputados_abaixo_meta_presenca', sa.Integer(), nullable=True, default=0),
        sa.Column('data_geracao', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.Column('fonte_dados', sa.String(length=100), nullable=True, default='Sistema_Kritikos'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('ano', 'mes', name='_resumo_mensal_uc')
    )
    op.create_index(op.f('ix_resumos_frequencia_mensal_id'), 'resumos_frequencia_mensal', ['id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - remove tabelas de frequência."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumos_frequencia_mensal_id'), table_name='resumos_frequencia_mensal')
    op.drop_table('resumos_frequencia_mensal')
    op.drop_index(op.f('ix_rankings_frequencia_id'), table_name='rankings_frequencia')
    op.drop_table('rankings_frequencia')
    op.drop_index(op.f('ix_detalhes_frequencia_id'), table_name='detalhes_frequencia')
    op.drop_table('detalhes_frequencia')
    op.drop_index(op.f('ix_frequencia_deputados_id'), table_name='frequencia_deputados')
    op.drop_table('frequencia_deputados')
    # ### end Alembic commands ###
