"""Criação inicial de todas as tabelas do projeto

Revision ID: e9e1f7bc1c91
Revises: 
Create Date: 2025-10-14 01:19:58.682898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9e1f7bc1c91'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deputados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_camara_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('nome_civil', sa.String(length=255), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('sexo', sa.CHAR(length=1), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('municipio_nascimento', sa.String(length=255), nullable=True),
    sa.Column('uf_nascimento', sa.CHAR(length=2), nullable=True),
    sa.Column('escolaridade', sa.String(length=100), nullable=True),
    sa.Column('profissao', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('foto_url', sa.String(), nullable=True),
    sa.Column('situacao', sa.String(length=50), nullable=True),
    sa.Column('condicao', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_deputados_api_camara_id'), 'deputados', ['api_camara_id'], unique=True)
    op.create_index(op.f('ix_deputados_id'), 'deputados', ['id'], unique=False)
    op.create_table('estados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.CHAR(length=2), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('regiao', sa.String(length=50), nullable=False),
    sa.Column('codigo_ibge', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sigla')
    )
    op.create_index(op.f('ix_estados_id'), 'estados', ['id'], unique=False)
    op.create_table('legislaturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_index(op.f('ix_legislaturas_id'), 'legislaturas', ['id'], unique=False)
    op.create_table('ods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('cor_oficial', sa.CHAR(length=7), nullable=True),
    sa.Column('icone_url', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_index(op.f('ix_ods_id'), 'ods', ['id'], unique=False)
    op.create_table('partidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.String(length=10), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('fundacao', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sigla')
    )
    op.create_index(op.f('ix_partidos_id'), 'partidos', ['id'], unique=False)
    op.create_table('proposicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_camara_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('ementa', sa.Text(), nullable=False),
    sa.Column('explicacao', sa.Text(), nullable=True),
    sa.Column('data_apresentacao', sa.Date(), nullable=False),
    sa.Column('situacao', sa.String(length=100), nullable=True),
    sa.Column('link_inteiro_teor', sa.String(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo', 'numero', 'ano', name='_proposicao_uc')
    )
    op.create_index(op.f('ix_proposicoes_api_camara_id'), 'proposicoes', ['api_camara_id'], unique=True)
    op.create_index(op.f('ix_proposicoes_id'), 'proposicoes', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('autorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposicao_id', sa.Integer(), nullable=False),
    sa.Column('deputado_id', sa.Integer(), nullable=False),
    sa.Column('tipo_autoria', sa.String(length=50), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposicao_id'], ['proposicoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposicao_id', 'deputado_id', 'tipo_autoria', name='_autoria_uc')
    )
    op.create_index(op.f('ix_autorias_id'), 'autorias', ['id'], unique=False)
    op.create_table('avaliacoes_par',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposicao_id', sa.Integer(), nullable=False),
    sa.Column('data_avaliacao', sa.Date(), nullable=False),
    sa.Column('escopo_impacto', sa.Integer(), nullable=True),
    sa.Column('alinhamento_ods', sa.Integer(), nullable=True),
    sa.Column('inovacao_eficiencia', sa.Integer(), nullable=True),
    sa.Column('sustentabilidade_fiscal', sa.Integer(), nullable=True),
    sa.Column('penalidade_oneracao', sa.Integer(), nullable=True),
    sa.Column('par_final', sa.Integer(), nullable=False),
    sa.Column('ods_identificados', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metodo_avaliacao', sa.String(length=50), nullable=True),
    sa.Column('avaliador_usuario_id', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['avaliador_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['proposicao_id'], ['proposicoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposicao_id')
    )
    op.create_index(op.f('ix_avaliacoes_par_id'), 'avaliacoes_par', ['id'], unique=False)
    op.create_table('calculos_idp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deputado_id', sa.Integer(), nullable=False),
    sa.Column('data_calculo', sa.Date(), nullable=False),
    sa.Column('periodo_referencia_inicio', sa.Date(), nullable=False),
    sa.Column('periodo_referencia_fim', sa.Date(), nullable=False),
    sa.Column('idp_final', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('desempenho_legislativo', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('par_relevancia_social', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('responsabilidade_fiscal', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('etica_legalidade', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('versao_metodologia', sa.String(length=10), nullable=True),
    sa.Column('detalhes_calculo', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deputado_id', 'data_calculo', 'periodo_referencia_inicio', name='_calculo_uc')
    )
    op.create_index(op.f('ix_calculos_idp_id'), 'calculos_idp', ['id'], unique=False)
    op.create_table('gastos_parlamentares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deputado_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('tipo_despesa', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('fornecedor_nome', sa.String(length=255), nullable=True),
    sa.Column('fornecedor_cnpj', sa.String(length=18), nullable=True),
    sa.Column('valor_documento', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_glosa', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_liquido', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('data_documento', sa.Date(), nullable=True),
    sa.Column('numero_documento', sa.String(length=255), nullable=True),
    sa.Column('numero_ressarcimento', sa.String(length=255), nullable=True),
    sa.Column('parcela', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gastos_parlamentares_ano'), 'gastos_parlamentares', ['ano'], unique=False)
    op.create_index(op.f('ix_gastos_parlamentares_id'), 'gastos_parlamentares', ['id'], unique=False)
    op.create_index(op.f('ix_gastos_parlamentares_mes'), 'gastos_parlamentares', ['mes'], unique=False)
    op.create_table('logs_sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('operacao', sa.String(length=100), nullable=False),
    sa.Column('tabela_afetada', sa.String(length=100), nullable=True),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('dados_anteriores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dados_novos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_sistema_id'), 'logs_sistema', ['id'], unique=False)
    op.create_table('mandatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deputado_id', sa.Integer(), nullable=False),
    sa.Column('legislatura_id', sa.Integer(), nullable=False),
    sa.Column('partido_id', sa.Integer(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('motivo_fim', sa.String(length=255), nullable=True),
    sa.Column('votos_recebidos', sa.Integer(), nullable=True),
    sa.Column('posicao_lista', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['estado_id'], ['estados.id'], ),
    sa.ForeignKeyConstraint(['legislatura_id'], ['legislaturas.id'], ),
    sa.ForeignKeyConstraint(['partido_id'], ['partidos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deputado_id', 'legislatura_id', name='_deputado_legislatura_uc')
    )
    op.create_index(op.f('ix_mandatos_id'), 'mandatos', ['id'], unique=False)
    op.create_table('pareceres_ccj',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposicao_id', sa.Integer(), nullable=False),
    sa.Column('data_parecer', sa.Date(), nullable=False),
    sa.Column('relator_deputado_id', sa.Integer(), nullable=True),
    sa.Column('parecer', sa.String(length=50), nullable=True),
    sa.Column('constitucionalidade', sa.String(length=50), nullable=True),
    sa.Column('juridicidade', sa.String(length=50), nullable=True),
    sa.Column('tecnica_legislativa', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['proposicao_id'], ['proposicoes.id'], ),
    sa.ForeignKeyConstraint(['relator_deputado_id'], ['deputados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pareceres_ccj_id'), 'pareceres_ccj', ['id'], unique=False)
    op.create_table('situacao_legal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deputado_id', sa.Integer(), nullable=False),
    sa.Column('tipo_situacao', sa.String(length=50), nullable=False),
    sa.Column('orgao_responsavel', sa.String(length=255), nullable=True),
    sa.Column('numero_processo', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('situacao_atual', sa.String(length=50), nullable=True),
    sa.Column('fonte_informacao', sa.String(length=255), nullable=True),
    sa.Column('url_fonte', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deputado_id', 'tipo_situacao', 'numero_processo', name='_situacao_legal_uc')
    )
    op.create_index(op.f('ix_situacao_legal_id'), 'situacao_legal', ['id'], unique=False)
    op.create_table('votacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_camara_id', sa.Integer(), nullable=True),
    sa.Column('proposicao_id', sa.Integer(), nullable=True),
    sa.Column('data_votacao', sa.TIMESTAMP(), nullable=False),
    sa.Column('objeto_votacao', sa.Text(), nullable=False),
    sa.Column('tipo_votacao', sa.String(length=50), nullable=True),
    sa.Column('resultado', sa.String(length=50), nullable=True),
    sa.Column('votos_sim', sa.Integer(), nullable=True),
    sa.Column('votos_nao', sa.Integer(), nullable=True),
    sa.Column('abstencoes', sa.Integer(), nullable=True),
    sa.Column('ausencias', sa.Integer(), nullable=True),
    sa.Column('quorum_minimo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proposicao_id'], ['proposicoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_votacoes_api_camara_id'), 'votacoes', ['api_camara_id'], unique=True)
    op.create_index(op.f('ix_votacoes_id'), 'votacoes', ['id'], unique=False)
    op.create_table('votos_deputados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('votacao_id', sa.Integer(), nullable=False),
    sa.Column('deputado_id', sa.Integer(), nullable=False),
    sa.Column('voto', sa.String(length=50), nullable=False),
    sa.Column('orientacao_partido', sa.String(length=50), nullable=True),
    sa.Column('seguiu_orientacao', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deputado_id'], ['deputados.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['votacao_id'], ['votacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('votacao_id', 'deputado_id', name='_voto_uc')
    )
    op.create_index(op.f('ix_votos_deputados_id'), 'votos_deputados', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votos_deputados_id'), table_name='votos_deputados')
    op.drop_table('votos_deputados')
    op.drop_index(op.f('ix_votacoes_id'), table_name='votacoes')
    op.drop_index(op.f('ix_votacoes_api_camara_id'), table_name='votacoes')
    op.drop_table('votacoes')
    op.drop_index(op.f('ix_situacao_legal_id'), table_name='situacao_legal')
    op.drop_table('situacao_legal')
    op.drop_index(op.f('ix_pareceres_ccj_id'), table_name='pareceres_ccj')
    op.drop_table('pareceres_ccj')
    op.drop_index(op.f('ix_mandatos_id'), table_name='mandatos')
    op.drop_table('mandatos')
    op.drop_index(op.f('ix_logs_sistema_id'), table_name='logs_sistema')
    op.drop_table('logs_sistema')
    op.drop_index(op.f('ix_gastos_parlamentares_mes'), table_name='gastos_parlamentares')
    op.drop_index(op.f('ix_gastos_parlamentares_id'), table_name='gastos_parlamentares')
    op.drop_index(op.f('ix_gastos_parlamentares_ano'), table_name='gastos_parlamentares')
    op.drop_table('gastos_parlamentares')
    op.drop_index(op.f('ix_calculos_idp_id'), table_name='calculos_idp')
    op.drop_table('calculos_idp')
    op.drop_index(op.f('ix_avaliacoes_par_id'), table_name='avaliacoes_par')
    op.drop_table('avaliacoes_par')
    op.drop_index(op.f('ix_autorias_id'), table_name='autorias')
    op.drop_table('autorias')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_proposicoes_id'), table_name='proposicoes')
    op.drop_index(op.f('ix_proposicoes_api_camara_id'), table_name='proposicoes')
    op.drop_table('proposicoes')
    op.drop_index(op.f('ix_partidos_id'), table_name='partidos')
    op.drop_table('partidos')
    op.drop_index(op.f('ix_ods_id'), table_name='ods')
    op.drop_table('ods')
    op.drop_index(op.f('ix_legislaturas_id'), table_name='legislaturas')
    op.drop_table('legislaturas')
    op.drop_index(op.f('ix_estados_id'), table_name='estados')
    op.drop_table('estados')
    op.drop_index(op.f('ix_deputados_id'), table_name='deputados')
    op.drop_index(op.f('ix_deputados_api_camara_id'), table_name='deputados')
    op.drop_table('deputados')
    # ### end Alembic commands ###
