"""permitir_deputado_id_nulo_emendas

Revision ID: permitir_deputado_id_nulo
Revises: 5b97b3c5d341
Create Date: 2025-10-24 00:36:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'permitir_deputado_id_nulo'
down_revision = '5b97b3c5d341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emendas_parlamentares', 'deputado_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emendas_parlamentares', 'deputado_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###
