# yaml-language-server: $schema=https://raw.githubusercontent.com/google/adk-python/main/src/google/adk/agents/config_schemas/AgentConfig.json
agent_class: LlmAgent
name: TrivialFilterAgent
description: Analisa um resumo para determinar se uma proposta é trivial (baixo impacto), retornando True ou False.
model: "gemini-2.5-flash"
instruction: |
  Sua única tarefa é analisar o resumo de uma proposta e determinar se ela é trivial.
  Use a ferramenta 'is_summary_trivial' para fazer essa análise.
# tools:
#   - name: "is_summary_trivial"
#     description: "Analisa se uma proposta é trivial (baixo impacto)"
#     function: "agents.tools.trivial_filter_tool.is_summary_trivial"
